import type { Category, SeasonalTheme, Transaction } from '../db/repositories';

const DAY_MS = 24 * 60 * 60 * 1000;

export interface SeasonalThemeCategorySpend {
  category: Category;
  spentMinor: number;
}

export interface SeasonalThemeStatus {
  spentMinor: number;
  /** `envelopeMinor - spentMinor` — can go negative ("restant négatif signalé, pas d'erreur"). */
  remainingMinor: number;
  /** `0` once the theme has ended. */
  daysRemaining: number;
  isEnded: boolean;
  categorySpend: SeasonalThemeCategorySpend[];
  /** Theme-category expenses from the last 7 days, most recent first — "dépenses de la semaine". */
  weeklyTransactions: Transaction[];
}

/**
 * "Enveloppe, restant, jours restants" per `docs/specs/mode-ramadan.md`. Pure function — only
 * sums **expense** transactions whose category was generated by this theme
 * (`Category.seasonalThemeId === theme.id`), never all spending during the date window, so a
 * regular "Alimentation" purchase during Ramadan doesn't count against the envelope
 * ("éviter le double comptage").
 */
export function computeSeasonalThemeStatus(
  theme: SeasonalTheme,
  categories: Category[],
  transactions: Transaction[],
  now: Date = new Date(),
): SeasonalThemeStatus {
  const themeCategories = categories.filter((category) => category.seasonalThemeId === theme.id);
  const themeCategoryIds = new Set(themeCategories.map((category) => category.id));
  const themeTransactions = transactions.filter(
    (transaction) => transaction.type === 'expense' && themeCategoryIds.has(transaction.categoryId),
  );

  const spentMinor = themeTransactions.reduce((sum, transaction) => sum + transaction.amountMinor, 0);
  const remainingMinor = theme.envelopeMinor - spentMinor;

  const endOfDay = new Date(`${theme.endDate}T23:59:59.999Z`).getTime();
  const rawDaysRemaining = Math.ceil((endOfDay - now.getTime()) / DAY_MS);
  const isEnded = rawDaysRemaining < 0;
  const daysRemaining = Math.max(0, rawDaysRemaining);

  const categorySpend: SeasonalThemeCategorySpend[] = themeCategories.map((category) => ({
    category,
    spentMinor: themeTransactions
      .filter((transaction) => transaction.categoryId === category.id)
      .reduce((sum, transaction) => sum + transaction.amountMinor, 0),
  }));

  const weekAgo = now.getTime() - 7 * DAY_MS;
  const weeklyTransactions = themeTransactions
    .filter((transaction) => {
      const occurredAtMs = new Date(transaction.occurredAt).getTime();
      return occurredAtMs >= weekAgo && occurredAtMs <= now.getTime();
    })
    .sort((a, b) => (a.occurredAt < b.occurredAt ? 1 : -1));

  return { spentMinor, remainingMinor, daysRemaining, isEnded, categorySpend, weeklyTransactions };
}
