import type { SupportedLanguage } from '../../i18n/i18n';

export type MemberRole = 'admin' | 'editor' | 'viewer';

/**
 * `role` only has real teeth once a shared cloud account exists (US-039/US-040, per
 * `docs/specs/profil-reglages.md`) — on this single-device MVP it's stored but not enforced
 * anywhere. Defaults to `'editor'` (matches how `seedDefaultMember`'s solo "Moi" member and any
 * locally-added member behave today: full local access). The household's creator gets `'admin'`
 * (US-005): admin implies edit rights, so `canEdit` covers both.
 */
export interface Member {
  id: string;
  name: string;
  role: MemberRole;
  createdAt: string;
  updatedAt: string;
}

export interface NewMember {
  name: string;
  role?: MemberRole;
}

export interface MemberPatch {
  name?: string;
  role?: MemberRole;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  color: string;
  isDefault: boolean;
  orderIndex: number;
  /** Set only for a sub-category generated by a `SeasonalTheme` activation (US-026) — `null` otherwise. */
  seasonalThemeId: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface NewCategory {
  name: string;
  icon: string;
  color: string;
  isDefault?: boolean;
  orderIndex?: number;
  seasonalThemeId?: string | null;
}

export interface CategoryPatch {
  name?: string;
  icon?: string;
  color?: string;
}

/** One active monthly cap + alert threshold per category — see `categoryBudgetRepository.ts`. */
export interface CategoryBudget {
  id: string;
  categoryId: string;
  /** `YYYY-MM` of the month this cap was last (re)configured. */
  month: string;
  capMinor: number;
  alertThresholdMinor: number;
  /** `YYYY-MM` of the last month a budget-alert notification was sent, or `null` if never. */
  lastAlertedMonth: string | null;
  /** "Reporter le reste au mois suivant" — see `computeCategoryBudgetStatus`'s rollover math. */
  rolloverEnabled: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface NewCategoryBudget {
  categoryId: string;
  month: string;
  capMinor: number;
  alertThresholdMinor: number;
  rolloverEnabled?: boolean;
}

export interface CategoryBudgetPatch {
  month?: string;
  capMinor?: number;
  alertThresholdMinor?: number;
  lastAlertedMonth?: string | null;
  rolloverEnabled?: boolean;
}

/** Single opt-in row for budget-alert notifications — see `notificationSettingsRepository.ts`. */
export interface NotificationSettings {
  budgetAlertsEnabled: boolean;
}

export type TransactionType = 'expense' | 'income';

/** Amount stored as an integer in the currency's minor unit (e.g. centimes) — never a float. */
export interface Transaction {
  id: string;
  type: TransactionType;
  amountMinor: number;
  currencyCode: string;
  categoryId: string;
  memberId: string;
  /** ISO 8601 UTC. */
  occurredAt: string;
  note: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface NewTransaction {
  type: TransactionType;
  amountMinor: number;
  currencyCode: string;
  categoryId: string;
  memberId: string;
  occurredAt: string;
  note?: string | null;
}

export interface TransactionPatch {
  type?: TransactionType;
  amountMinor?: number;
  currencyCode?: string;
  categoryId?: string;
  memberId?: string;
  occurredAt?: string;
  note?: string | null;
}

export type RecurringFrequency = 'monthly' | 'weekly';
export type RecurringMode = 'auto' | 'prompt';

/**
 * A recurring rule template (US-021, `docs/specs/transactions-recurrentes.md`) — never a
 * transaction itself. `recurringOccurrences.ts`'s `computeDueOccurrenceDates` is what turns this
 * into concrete due dates; creating/proposing the actual `Transaction` rows from those dates is a
 * later story's runtime, not this repository's job (editing `amountMinor` etc. here therefore
 * only ever affects future occurrences — past transactions already created are separate rows).
 */
export interface RecurringRule {
  id: string;
  type: TransactionType;
  amountMinor: number;
  currencyCode: string;
  categoryId: string;
  memberId: string;
  frequency: RecurringFrequency;
  /** 1-31, only set for `frequency: 'monthly'` (clamped to the shorter month's last day). */
  dayOfMonth: number | null;
  /** 0 (Sunday) - 6 (Saturday), only set for `frequency: 'weekly'`. */
  weekday: number | null;
  /** ISO date `YYYY-MM-DD` — first possible occurrence. */
  startDate: string;
  /** ISO date `YYYY-MM-DD`, or `null` for no end. */
  endDate: string | null;
  mode: RecurringMode;
  paused: boolean;
  /** ISO date `YYYY-MM-DD` of the last occurrence proposed/created, or `null` if never. */
  lastRunDate: string | null;
  note: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface NewRecurringRule {
  type: TransactionType;
  amountMinor: number;
  currencyCode: string;
  categoryId: string;
  memberId: string;
  frequency: RecurringFrequency;
  dayOfMonth?: number | null;
  weekday?: number | null;
  startDate: string;
  endDate?: string | null;
  mode: RecurringMode;
  paused?: boolean;
  note?: string | null;
}

export interface RecurringRulePatch {
  type?: TransactionType;
  amountMinor?: number;
  currencyCode?: string;
  categoryId?: string;
  memberId?: string;
  frequency?: RecurringFrequency;
  dayOfMonth?: number | null;
  weekday?: number | null;
  startDate?: string;
  endDate?: string | null;
  mode?: RecurringMode;
  paused?: boolean;
  lastRunDate?: string | null;
  note?: string | null;
}

/**
 * A savings vault/goal (US-023, `docs/specs/objectifs-coffres.md`) — "coffre". `deadline: null`
 * is a legitimate, first-class state (fonds d'urgence sans échéance), not a missing value:
 * `computeVaultStatus` never imposes a dated monthly suggestion on those.
 */
export interface Vault {
  id: string;
  name: string;
  targetMinor: number;
  currencyCode: string;
  /** ISO date `YYYY-MM-DD`, or `null` for no deadline (e.g. an emergency fund). */
  deadline: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface NewVault {
  name: string;
  targetMinor: number;
  currencyCode: string;
  deadline?: string | null;
}

export interface VaultPatch {
  name?: string;
  targetMinor?: number;
  currencyCode?: string;
  deadline?: string | null;
}

/** A single deposit toward a `Vault` — "versement", journaled and never withdrawn from a real account. */
export interface VaultContribution {
  id: string;
  vaultId: string;
  amountMinor: number;
  memberId: string;
  /** ISO 8601 UTC, same convention as `Transaction.occurredAt`. */
  date: string;
  note: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface NewVaultContribution {
  vaultId: string;
  amountMinor: number;
  memberId: string;
  date: string;
  note?: string | null;
}

/**
 * A tontine/daret group (US-024, `docs/specs/tontine.md`). Suivi uniquement — Mizaniyati ne
 * collecte, ne détient ni ne transfère aucun argent (`.claude/rules/legal-disclaimers.md`).
 */
export interface TontineGroup {
  id: string;
  name: string;
  contributionPerRoundMinor: number;
  currencyCode: string;
  memberCount: number;
  /** ISO `YYYY-MM` — the month round 1 starts. */
  startMonth: string;
  /** Opt-in reminder before the current round's payment is due. */
  reminderEnabled: boolean;
  /** `YYYY-MM` of the last month a payment-reminder notification fired, or `null` if never. */
  lastRemindedMonth: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface NewTontineGroup {
  name: string;
  contributionPerRoundMinor: number;
  currencyCode: string;
  memberCount: number;
  startMonth: string;
  reminderEnabled?: boolean;
}

export interface TontineGroupPatch {
  name?: string;
  contributionPerRoundMinor?: number;
  reminderEnabled?: boolean;
  lastRemindedMonth?: string | null;
}

/**
 * A participant in a `TontineGroup` — deliberately its own `name` string, not a foreign key into
 * the household `Member` table, since a tontine typically includes people outside the household.
 * `isSelf` marks the single participant representing this household (there is exactly one per
 * group) — the anchor "findMyRound" (`src/tontine/tontineStatus.ts`) uses to derive "mon tour".
 */
export interface TontineMember {
  id: string;
  groupId: string;
  name: string;
  /** 1-indexed position in the payout order — also the round number this member benefits from. */
  roundOrder: number;
  isSelf: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface NewTontineMember {
  groupId: string;
  name: string;
  roundOrder: number;
  isSelf?: boolean;
}

/**
 * One payout round of a `TontineGroup` — generated once at group creation and never edited,
 * except for `closedAt`: set once the organizer explicitly closes the round after every member
 * has paid (US-039). Closure is bookkeeping only — it never changes which round is "current"
 * (`findCurrentRound` stays month-based).
 */
export interface TontineRound {
  id: string;
  groupId: string;
  roundNumber: number;
  /** ISO `YYYY-MM`. */
  month: string;
  beneficiaryMemberId: string;
  /** ISO timestamp once the organizer closes the round, `null` while still open. */
  closedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface NewTontineRound {
  groupId: string;
  roundNumber: number;
  month: string;
  beneficiaryMemberId: string;
}

export interface TontineRoundPatch {
  closedAt?: string | null;
}

export type TontinePaymentStatus = 'paid' | 'pending';

/** One member's contribution status for one round — "6/8 payé" is a count of these. */
export interface TontinePayment {
  id: string;
  roundId: string;
  memberId: string;
  status: TontinePaymentStatus;
  paidAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface NewTontinePayment {
  roundId: string;
  memberId: string;
  status?: TontinePaymentStatus;
}

export interface TontinePaymentPatch {
  status?: TontinePaymentStatus;
  paidAt?: string | null;
}

export type ZakatNisabBasis = 'gold' | 'silver';

/**
 * Single fixed-`id='default'` row (US-025, `docs/specs/zakat.md`) — mirrors
 * `notification_settings`'s one-row-per-household convention. No live gold/silver price feed is
 * wired up yet (`docs/PRD.md` §8 leaves the FX/gold provider open) — prices are always
 * manually entered, kept per metal so switching `nisabBasis` doesn't lose the other one's price.
 */
export interface ZakatConfig {
  madhhab: string;
  nisabBasis: ZakatNisabBasis;
  goldPricePerGramMinor: number | null;
  silverPricePerGramMinor: number | null;
  /** ISO 8601 UTC of the last manual price entry, or `null` if never set. */
  priceUpdatedAt: string | null;
}

export interface ZakatConfigPatch {
  madhhab?: string;
  nisabBasis?: ZakatNisabBasis;
  goldPricePerGramMinor?: number | null;
  silverPricePerGramMinor?: number | null;
}

/**
 * A saved calculation — "enregistrer/planifier le don" per the spec (US-043). The core fields
 * (amounts, `createdAt`) are never edited once created; `paidAt`/`transactionId` are the one thing
 * that *does* change, the moment the household marks the plan as paid. `paidAt === null` is the
 * sole "still planned" signal — no separate status enum that could disagree with it.
 */
export interface ZakatAssessment {
  id: string;
  cashMinor: number;
  goldSilverMinor: number;
  investmentsMinor: number;
  debtsMinor: number;
  baseMinor: number;
  dueMinor: number;
  aboveNisab: boolean;
  /** ISO `YYYY-MM-DD` the household intends to pay by, or `null` if not planned for a date. */
  dueDate: string | null;
  /** Set once marked paid; `null` means still planned. */
  paidAt: string | null;
  /** The expense `Transaction` created for the "Zakat & dons" category once paid, or `null`. */
  transactionId: string | null;
  /** Set once the due-date reminder has fired, so it is never sent twice for the same plan. */
  remindedAt: string | null;
  createdAt: string;
}

export interface NewZakatAssessment {
  cashMinor: number;
  goldSilverMinor: number;
  investmentsMinor: number;
  debtsMinor: number;
  baseMinor: number;
  dueMinor: number;
  aboveNisab: boolean;
  dueDate?: string | null;
}

export interface ZakatAssessmentPaidPatch {
  paidAt: string;
  transactionId: string;
}

/**
 * A single money transfer a diaspora household sends "back home" (US-045) — append-only, like
 * `ZakatAssessment`. Not to be confused with `Transfer`, an unrelated feature (a "virement"
 * between two members *within* the same household).
 */
export interface DiasporaTransfer {
  id: string;
  amountMinor: number;
  currencyCode: string;
  /** ISO 8601 date/time the transfer was sent. */
  occurredAt: string;
  createdAt: string;
}

export interface NewDiasporaTransfer {
  amountMinor: number;
  currencyCode: string;
  occurredAt: string;
}

export type SeasonalThemeType = 'ramadan' | 'aid_kebir' | 'back_to_school';

/**
 * A seasonal budget theme (US-026, `docs/specs/mode-ramadan.md`) — generic engine, only
 * `'ramadan'` is wired up to a screen for MVP (`aid_kebir`/`back_to_school` are post-MVP per the
 * spec, but the model already supports them so activating a second theme type later is just a
 * new `type` value, not a new table). The actual expenses stay plain `Transaction` rows against
 * `Category`s tagged with this theme's id (`Category.seasonalThemeId`) — there is no separate
 * "seasonal expense" entity.
 */
export interface SeasonalTheme {
  id: string;
  type: SeasonalThemeType;
  active: boolean;
  /** ISO date `YYYY-MM-DD` — manually adjustable, since the Hijri calendar source is uncertain. */
  startDate: string;
  endDate: string;
  envelopeMinor: number;
  currencyCode: string;
  createdAt: string;
  updatedAt: string;
}

export interface NewSeasonalTheme {
  type: SeasonalThemeType;
  active?: boolean;
  startDate: string;
  endDate: string;
  envelopeMinor: number;
  currencyCode: string;
}

export interface SeasonalThemePatch {
  active?: boolean;
  startDate?: string;
  endDate?: string;
  envelopeMinor?: number;
}

export type SubscriptionStatus = 'trial' | 'active' | 'expired';

/**
 * Single fixed-`id='default'` row (US-029, `docs/specs/plans-abonnements.md`) — mirrors
 * `zakat_config`'s one-row convention. **No row at all means the household is on the free
 * plan** — `subscriptionRepository.getSubscription` returns `null` in that case rather than a
 * default object, so `resolveActivePlan` (`src/subscriptions/`) can tell "never subscribed" apart
 * from "subscribed and it lapsed".
 */
export interface Subscription {
  planId: string;
  status: SubscriptionStatus;
  /** ISO 8601 UTC — set for `status: 'trial'`, `null` otherwise. */
  trialEndsAt: string | null;
  /** ISO 8601 UTC — set for `status: 'active'` (a real recurring purchase), `null` otherwise. */
  renewsAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface NewSubscription {
  planId: string;
  status: SubscriptionStatus;
  trialEndsAt?: string | null;
  renewsAt?: string | null;
}

/**
 * Only `'language_country'` exists today (US-023, the only onboarding step this story builds).
 * US-024 (confidentialité) / US-025 (compte local vs cloud) will widen this union as they add
 * their own steps to the sequence described in `docs/specs/onboarding-confidentialite.md`.
 */
export type OnboardingStep = 'language_country' | 'privacy';

/**
 * Single fixed-`id='default'` row (US-023, `docs/specs/onboarding-confidentialite.md`'s
 * `userSettings` model) — mirrors `subscriptions`'s one-row convention. **No row at all means
 * onboarding hasn't been completed** — `getUserSettings` returns `null` in that case, which is
 * what `App.tsx`'s startup gate checks to decide whether to show the onboarding flow.
 */
export interface UserSettings {
  languageCode: SupportedLanguage;
  countryCode: string;
  currencyCode: string;
  onboardingStep: OnboardingStep;
  /** When the household accepted the privacy commitments (US-004); `null` until they do. */
  privacyAcceptedAt: string | null;
  /** How many transactions the household has dictated (US-014). */
  voiceEntryCount: number;
  /** The household closed the voice discovery banner (US-014). */
  voicePromoDismissed: boolean;
  /** The contextual mic-permission explainer (US-020a) has been shown at least once. */
  micPermissionExplainerSeen: boolean;
  /** The approximate Hijri year the household last dismissed the Ramadan activation suggestion
   * (US-041), or `null` if never dismissed — a year, not a boolean, so it resurfaces next year. */
  ramadanSuggestionDismissedHijriYear: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface NewUserSettings {
  languageCode: SupportedLanguage;
  countryCode: string;
  currencyCode: string;
}

/**
 * The family budget container ("foyer"). The MVP runs a single implicit household, but the entity
 * is modeled explicitly so shared/cloud accounts (US-039/US-040) can attach members and data to a
 * named household later without a schema rewrite.
 */
export interface Household {
  id: string;
  name: string;
  currencyCode: string;
  createdAt: string;
  updatedAt: string;
}

export interface NewHousehold {
  name: string;
  currencyCode: string;
}

export interface HouseholdPatch {
  name?: string;
  currencyCode?: string;
}

/** Whether a debt is money owed *to* the household or money the household *owes*. */
export type DebtDirection = 'owed_to_household' | 'household_owes';

/**
 * A tracked debt ("dette") between the household and a free-text counterparty (a person or shop —
 * not an app member, since debts often involve people outside the household). Journaled only: no
 * real account is settled, `settled` just flips the local status.
 */
export interface Debt {
  id: string;
  label: string;
  counterparty: string;
  direction: DebtDirection;
  amountMinor: number;
  currencyCode: string;
  /** ISO date `YYYY-MM-DD`, or `null` for a debt with no agreed due date. */
  dueDate: string | null;
  settled: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface NewDebt {
  label: string;
  counterparty: string;
  direction: DebtDirection;
  amountMinor: number;
  currencyCode: string;
  dueDate?: string | null;
  settled?: boolean;
}

export interface DebtPatch {
  label?: string;
  counterparty?: string;
  direction?: DebtDirection;
  amountMinor?: number;
  currencyCode?: string;
  dueDate?: string | null;
  settled?: boolean;
}

/**
 * A transfer ("virement") moving money between two household members. Journaled locally like every
 * other movement — it never touches a real bank account, only the local ledger.
 */
export interface Transfer {
  id: string;
  amountMinor: number;
  currencyCode: string;
  fromMemberId: string;
  toMemberId: string;
  /** ISO date `YYYY-MM-DD`. */
  date: string;
  note: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface NewTransfer {
  amountMinor: number;
  currencyCode: string;
  fromMemberId: string;
  toMemberId: string;
  date: string;
  note?: string | null;
}

export interface TransferPatch {
  amountMinor?: number;
  currencyCode?: string;
  fromMemberId?: string;
  toMemberId?: string;
  date?: string;
  note?: string | null;
}
